version: '3.8'

services:
  react-app:
    build:
      context: ./vidtranscode
    container_name: react
    expose:
      - "80"  # Exposing this port internally for Nginx to serve static files
    depends_on:
      - node-server

  node-server:
    build:
      context: ./vid-api2
    container_name: node
    expose:
      - "5000"  # Expose this port internally for Nginx to forward API requests
    environment:
      - PORT=5000
      - aws_access_key_id=ASIA5DYSEEJ47KF3E64Y
      - aws_secret_access_key=LFbqzjHzrK+/tWImbqE1VaF6yNTycLGzAE5YvLoO
      - aws_session_token=IQoJb3JpZ2luX2VjEJb//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAMDgdlobrtc2Hs8Ev/SBDfPuZ2b58DK/Hka0lIr3PyQOAiBsUdUqw59S4LVE07eu+MFm4VFvYi+bwhKqKbfi4xqN+yquAwjP//////////8BEAMaDDkwMTQ0NDI4MDk1MyIMtP2GnvbnMbcbK5XPKoIDQsTvFPJZAiTnz4wuZNgjlJTESPgwbtnakBPSi0SsiVp/t3XlE7YguA3frxvxYjdDr6uyoZf6wG5DfSVlzSD/SFQxG83TUiXU884r5LQgOe16/YjXrtyL9fTXzJlJwrG9oq7dZXodB6TgwGQFZmHeBcvm1YFZse65NI7BGQKNsHH8jOxQc473aDFgzzqSKeTSdLk9F31B4rvb4KMRdRmFqgroCHAtLpm4Rs3HLvIUdMqa8fOd05X5PCrGkW5pvkNYGIqPI4MHFpFQWEVZOvu/8Pc8RIEOupoY0Cv6bf71+0bL/QJA2E8JLnUW8UOA+WmnPhA5PUruzottSLsS+mOz64jUhROMLe9GVgdNS9XD4xjxs52I10srH9VYv6yKns1WVyI3MlkjWu+XkkFnlY/amKW8SFkH3m58UNEtH9BaxgIhdPZWVCLgSfy9mH7XuKTrfGfz8bPzQSuy7PLtkB3IniBMI4wh/aRiUjiUEpci+7hLWo8CxfG34hQqZKQs3NyyMWcwjJ7JtwY6pgH1bmsXUuL+Nn4jCbdcfh/sKBDTMNRR9RgXong4QCfFwcNEhUzaQ3LBKWYOklPyfGnw98CRnFgXNHu6/r6hXnlEDzuCsi7JNlAxI+ThC+yv68IIH8EdutJRbnuHrfVuKQeJQP9RlcAHIhe+K014Uox0U7akszIQYTZrPZdk6r3AAcJCrkSW+NMKNpZV6InMq/8VN6yKetTMtX7YoMLtZD6Wm7zelE14

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
    ports:
      - "80:80"  # Expose Nginx to the host on port 80
    depends_on:
      - react-app
      - node-server
